image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: ignore
  - port: 3306
    onOpen: notify
  - port: 5005
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 8081
    onOpen: ignore
  - port: 9000-9999
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: false
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false